# Generated by Django 5.0.6 on 2024-05-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_paper_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='views_count',
        ),
    ]
