# Generated by Django 5.0.6 on 2024-05-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_paper_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='article',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='title',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
        migrations.AddField(
            model_name='paper',
            name='article_en',
            field=models.TextField(blank=True, null=True, verbose_name='Article (EN)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='article_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Article (UZ)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description (UZ)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (EN)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='keywords_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (UZ)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (UZ)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description (UZ)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (UZ)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
