# Generated by Django 5.0.6 on 2024-05-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_paper_article_remove_paper_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='article_en',
            field=models.TextField(verbose_name='Article (EN)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='article_uz',
            field=models.TextField(null=True, verbose_name='Article (UZ)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description_en',
            field=models.TextField(verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description (UZ)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords_en',
            field=models.CharField(max_length=255, verbose_name='Keywords (EN)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Keywords (UZ)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title (UZ)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_en',
            field=models.TextField(verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description (UZ)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title (UZ)'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
